# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
  
baseurl: "jekyll-material-design-lite" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

#customize your colors: http://www.getmdl.io/customize/index.html
primary_color: blue_grey
accent_color: orange

google_analytics:

# Build settings
markdown: redcarpet

excerpt_separator: <!--more-->

#redcarpet:
#  extensions: ["smart", "tables", "no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data"]

gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem